global:
  canary:
    enabled: false
    tag: "2.0.0"
  tls:
    enabled: true
    email: richardbieringa@gmail.com
    certName: ingress-cert
    namespace: istio-system
    cloudFlareAPIToken: M0qxSgZbgyv9nu-K-y7JL4_y0FmE1PexyRp1QvJX
    dnsNames:
      - richardbieringa.live

postgresql:
  postgresqlUsername: software-containerization
  postgresqlPassword: super-secret-password
  postgresqlDatabase: sc-users

api:
  image:
    tag: "1.0.1"
  replicaCount: 1
  dbConfig:
    DB_USER: software-containerization
    DB_PASSWORD: super-secret-password
    DB_NAME: sc-users
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50

frontend:
  image:
    tag: "1.2.0"
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
