apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
data:
  config.json: |-
    {
        "endpoint": "{{ .Values.apiEndpoint }}"
    }
  nginx.conf: |-
    worker_processes 4;

    events { worker_connections 1024; }

    http {
        server {
            listen 80;
            root  /usr/share/nginx/html;
            include /etc/nginx/mime.types;

            location {{ .Values.frontendPath }} {
                proxy_http_version 1.1;
                try_files $uri /index.html;
            }

            location {{ .Values.frontendApiPath }} {
                proxy_pass http://{{ .Release.Name }}-api/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header HOST $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass_request_headers on;
            }
        }
    }