apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  hosts:
    - "richardbieringa.live"
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - name: frontend-http-route
      match:
      - uri:
          prefix: /
      route:
      - destination:
          host: {{ include "frontend.fullname" . }}
          subset: live
          port:
            number: 80
      {{- if .Values.global.canary.enabled }}
        weight: 50
      - destination:
          host: {{ include "frontend.fullname" . }}
          subset: canary
          port:
            number: 80
        weight: 50
      {{- end }}