apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
data:
  API_PORT: {{ .Values.apiPort | default 80 | quote }}
  {{- with .Values.dbConfig }}
  DB_USER: {{ .DB_USER | quote }}
  DB_HOST: "{{ $.Release.Name }}-postgresql"
  DB_PORT: {{ .DB_PORT | default 5432 | quote }}
  DB_NAME: {{ .DB_NAME | quote }}
  {{- end }}