apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cf-api-token
  namespace: {{ .Values.global.tls.namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.global.tls.cloudFlareAPIToken }}